class SkillsData {
  static List<String> skillsList = [
    'Computer Programmers',
    'Web Developers',
    'Computer Numerically Controlled Tool Programmers',
    'Video Game Designers',
    'Data Warehousing Specialists',
    'Software Quality Assurance Analysts and Testers',
    'Computer and Information Research Scientists',
    'Network and Computer Systems Administrators',
    'Computer Network Architects',
    'Computer Systems Engineers/Architects',
    'Biostatisticians',
    'Database Administrators',
    'Physicists',
    'Database Architects',
    'Clinical Data Managers',
    'Robotics Engineers',
    'Computer Systems Analysts',
    'Bioinformatics Technicians',
    'Web Administrators',
    'Statisticians',
    'Bioengineers and Biomedical Engineers',
    'Statistical Assistants',
    'Computer Science Teachers, Postsecondary',
    'Robotics Technicians',
    'Geographic Information Systems Technologists and Technicians',
    'Biologists',
    'Industrial-Organizational Psychologists',
    'Remote Sensing Technicians',
    'Health Informatics Specialists',
    'Computer and Information Systems Managers',
    'Computer Numerically Controlled Tool Operators',
    'Search Marketing Strategists',
    'Financial Quantitative Analysts',
    'Automotive Engineers',
    'Mining and Geological Engineers, Including Mining Safety Engineers',
    'Electronics Engineers, Except Computer',
    'Social Science Research Assistants',
    'Desktop Publishers',
    'Business Intelligence Analysts',
    'Microsystems Engineers',
    'Information Security Analysts',
    'Logistics Engineers',
    'Actuaries',
    'Computer Hardware Engineers',
    'Operations Research Analysts',
    'Mathematicians',
    'Mechanical Engineers',
    'Remote Sensing Scientists and Technologists',
    'Document Management Specialists',
    'Radio Frequency Identification Device Specialists',
    'Geodetic Surveyors',
    'Chemical Engineers',
    'Nanosystems Engineers',
    'Telecommunications Engineering Specialists',
    'Online Merchants',
    'Photographic Process Workers and Processing Machine Operators',
    'Biochemists and Biophysicists',
    'Photonics Engineers',
    'Human Factors Engineers and Ergonomists',
    'Mechanical Drafters',
    'Survey Researchers',
    'Astronomers',
    'Electro-Mechanical and Mechatronics Technologists and Technicians',
    'Environmental Restoration Planners',
    'Nanotechnology Engineering Technologists and Technicians',
    'Information Technology Project Managers',
    'Photonics Technicians',
    'Precision Agriculture Technicians',
    'Computer Network Support Specialists',
    'Fuel Cell Engineers',
    'Mechatronics Engineers',
    'Electrical and Electronic Engineering Technologists and Technicians',
    'Hydrologists',
    'Molecular and Cellular Biologists',
    'Transportation Engineers',
    'Water/Wastewater Engineers',
    'Computer User Support Specialists',
    'Electrical and Electronics Repairers, Commercial and Industrial Equipment',
    'Environmental Engineering Technologists and Technicians',
    'Market Research Analysts and Marketing Specialists',
    'Soil and Plant Scientists',
    'Automotive Engineering Technicians',
    'Broadcast Technicians',
    'Sales Engineers',
    'Chemists',
    'Aerospace Engineering and Operations Technologists and Technicians',
    'Agricultural Engineers',
    'Biofuels Production Managers',
    'Solar Energy Systems Engineers',
    'Special Effects Artists and Animators',
    'Audiovisual Equipment Installers and Repairers',
    'Hydroelectric Production Managers',
    'Computer, Automated Teller, and Office Machine Repairers',
    'Patternmakers, Metal and Plastic',
    'Aerospace Engineers',
    'Bioinformatics Scientists',
    'Wind Energy Engineers',
    'Marine Engineers and Naval Architects',
    'Architectural and Civil Drafters',
    'Environmental Scientists and Specialists, Including Health',
    'Microbiologists',
    'Industrial Ecologists',
    'Intelligence Analysts',
    'Medical and Clinical Laboratory Technologists',
    'Brokerage Clerks',
    'Economists',
    'Logistics Analysts',
    'Transportation Planners',
    'Engineering Teachers, Postsecondary',
    'Forest and Conservation Technicians',
    'Geoscientists, Except Hydrologists and Geographers',
    'Medical Scientists, Except Epidemiologists',
    'Telecommunications Equipment Installers and Repairers, Except Line Installers',
    'Electrical Engineers',
    'Health and Safety Engineers, Except Mining Safety Engineers and Inspectors',
    'Quality Control Systems Managers',
    'Atmospheric and Space Scientists',
    'Biofuels/Biodiesel Technology and Product Development Managers',
    'Geography Teachers, Postsecondary',
    'Audio and Video Technicians',
    'Business Continuity Planners',
    'Energy Engineers, Except Wind and Solar',
    'Fabric and Apparel Patternmakers',
    'Mechanical Engineering Technologists and Technicians',
    'Nuclear Power Reactor Operators',
    'Radio, Cellular, and Tower Equipment Installers and Repairers',
    'Traffic Technicians',
    'Billing and Posting Clerks',
    'Cytotechnologists',
    'Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products',
    'Signal and Track Switch Repairers',
    'Surveying and Mapping Technicians',
    'Manufacturing Engineers',
    'Civil Engineers',
    'Biological Technicians',
    'Environmental Economists',
    'Logisticians',
    'Materials Engineers',
    'Physicians, Pathologists',
    'Cost Estimators',
    'Fire-Prevention and Protection Engineers',
    'Industrial Engineering Technologists and Technicians',
    'Natural Sciences Managers',
    'Commercial and Industrial Designers',
    'Conservation Scientists',
    'Equal Opportunity Representatives and Officers',
    'Hydroelectric Plant Technicians',
    'Surveyors',
    'Water Resource Specialists',
    'Customs Brokers',
    'Economics Teachers, Postsecondary',
    'Regulatory Affairs Specialists',
    'Architects, Except Landscape and Naval',
    'Business Teachers, Postsecondary',
    'Climate Change Policy Analysts',
    'Executive Secretaries and Executive Administrative Assistants',
    'Geothermal Production Managers',
    'Marketing Managers',
    'Petroleum Pump System Operators, Refinery Operators, and Gaugers',
    'Sports Medicine Physicians',
    'Wind Energy Operations Managers',
    'Advertising Sales Agents',
    'Architectural and Engineering Managers',
    'Budget Analysts',
    'Cartographers and Photogrammetrists',
    'Chemistry Teachers, Postsecondary',
    'Chief Sustainability Officers',
    'Dermatologists',
    'Electrical and Electronics Repairers, Powerhouse, Substation, and Relay',
    'Electronic Equipment Installers and Repairers, Motor Vehicles',
    'Exercise Physiologists',
    'First-Line Supervisors of Mechanics, Installers, and Repairers',
    'Forestry and Conservation Science Teachers, Postsecondary',
    'Geneticists',
    'Geothermal Technicians',
    'Industrial Engineers',
    'Interviewers, Except Eligibility and Loan',
    'Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
    'Neurodiagnostic Technologists',
    'Nursing Instructors and Teachers, Postsecondary',
    'Occupational Health and Safety Technicians',
    'Optometrists',
    'Petroleum Engineers',
    'Physician Assistants',
    'Physics Teachers, Postsecondary',
    'Purchasing Managers',
    'Animal Scientists',
    'Architecture Teachers, Postsecondary',
    'Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary',
    'Civil Engineering Technologists and Technicians',
    'Cutting and Slicing Machine Setters, Operators, and Tenders',
    'First-Line Supervisors of Office and Administrative Support Workers',
    'Materials Scientists',
    'Medical and Clinical Laboratory Technicians',
    'Mental Health and Substance Abuse Social Workers',
    'Psychology Teachers, Postsecondary',
    'Validation Engineers',
    'Art Therapists',
    'Meter Readers, Utilities',
    'Preventive Medicine Physicians',
    'Reservation and Transportation Ticket Agents and Travel Clerks',
    'Securities, Commodities, and Financial Services Sales Agents',
    'Compensation, Benefits, and Job Analysis Specialists',
    'Farm and Home Management Educators',
    'Industrial Machinery Mechanics',
    'Human Resources Managers',
    'Urban and Regional Planners',
    'Anthropologists and Archeologists',
    'Camera and Photographic Equipment Repairers',
    'Forensic Science Technicians',
    'Government Property Inspectors and Investigators',
    'Occupational Health and Safety Specialists',
    'Wind Energy Development Managers',
    'Compliance Officers',
    'Environmental Engineers',
    'Environmental Science and Protection Technicians, Including Health',
    'Loan Interviewers and Clerks',
    'Machinists',
    'Media Technical Directors/Managers',
    'Non-Destructive Testing Specialists',
    'Nuclear Engineers',
    'Radiation Therapists',
    'Weighers, Measurers, Checkers, and Samplers, Recordkeeping',
    'Woodworking Machine Setters, Operators, and Tenders, Except Sawing',
    'Zoologists and Wildlife Biologists',
    'Geological Technicians, Except Hydrologic Technicians',
    'Area, Ethnic, and Cultural Studies Teachers, Postsecondary',
    'Audiologists',
    'Career/Technical Education Teachers, Secondary School',
    'Chemical Plant and System Operators',
    'Curators',
    'Data Entry Keyers',
    'Dietitians and Nutritionists',
    'Educational, Guidance, and Career Counselors and Advisors',
    'Electrical and Electronics Drafters',
    'First-Line Supervisors of Police and Detectives',
    'First-Line Supervisors of Retail Sales Workers',
    'Fraud Examiners, Investigators and Analysts',
    'Medical and Health Services Managers',
    'Mixing and Blending Machine Setters, Operators, and Tenders',
    'Occupational Therapists',
    'Park Naturalists',
    'Personal Financial Advisors',
    'Physical Therapist Assistants',
    'Private Detectives and Investigators',
    'Social Work Teachers, Postsecondary',
    'Solar Energy Installation Managers',
    'Sound Engineering Technicians',
    'Special Education Teachers, Preschool',
    'Special Education Teachers, Secondary School',
    'Substance Abuse and Behavioral Disorder Counselors',
    'Teaching Assistants, Postsecondary',
    'Agricultural Sciences Teachers, Postsecondary',
    'Archivists',
    'Compliance Managers',
    'Critical Care Nurses',
    'Electric Motor, Power Tool, and Related Repairers',
    'Fitness and Wellness Coordinators',
    'Foreign Language and Literature Teachers, Postsecondary',
    'General Internal Medicine Physicians',
    'Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic',
    'Hotel, Motel, and Resort Desk Clerks',
    'Interior Designers',
    'Magnetic Resonance Imaging Technologists',
    'Management Analysts',
    'Mathematical Science Teachers, Postsecondary',
    'Model Makers, Metal and Plastic',
    'Neurologists',
    'Office Machine Operators, Except Computer',
    'Patient Representatives',
    'Physical Medicine and Rehabilitation Physicians',
    'Postmasters and Mail Superintendents',
    'Power Distributors and Dispatchers',
    'Prepress Technicians and Workers',
    'Public Safety Telecommunicators',
    'Security and Fire Alarm Systems Installers',
    'Service Unit Operators, Oil and Gas',
    'Set and Exhibit Designers',
    'Social and Community Service Managers',
    'Speech-Language Pathologists',
    'Wholesale and Retail Buyers, Except Farm Products',
    'Word Processors and Typists',
    'Advertising and Promotions Managers',
    'Air Traffic Controllers',
    'Automotive Body and Related Repairers',
    'Biomass Plant Technicians',
    'Career/Technical Education Teachers, Middle School',
    'Cooling and Freezing Equipment Operators and Tenders',
    'Directors, Religious Activities and Education',
    'Education Administrators, Kindergarten through Secondary',
    'Engine and Other Machine Assemblers',
    'Family and Consumer Sciences Teachers, Postsecondary',
    'Farm Equipment Mechanics and Service Technicians',
    'Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
    'Human Resources Assistants, Except Payroll and Timekeeping',
    'Insurance Sales Agents',
    'Law Teachers, Postsecondary',
    'Library Science Teachers, Postsecondary',
    'Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Ophthalmic Laboratory Technicians',
    'Orthoptists',
    'Philosophy and Religion Teachers, Postsecondary',
    'Power Plant Operators',
    'Pump Operators, Except Wellhead Pumpers',
    'Quality Control Analysts',
    'Regulatory Affairs Managers',
    'School Psychologists',
    'Secondary School Teachers, Except Special and Career/Technical Education',
    'Self-Enrichment Teachers',
    'Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders',
    'Ship Engineers',
    'Textile Cutting Machine Setters, Operators, and Tenders',
    'Training and Development Managers',
    'Travel Agents',
    'Veterinary Technologists and Technicians',
    'Investment Fund Managers',
    'Fire Inspectors and Investigators',
    'Automotive Service Technicians and Mechanics',
    'Detectives and Criminal Investigators',
    'Producers and Directors',
    'Environmental Compliance Inspectors',
    'Accountants and Auditors',
    'Biofuels Processing Technicians',
    'Credit Analysts',
    'Financial Examiners',
    'Radiologists',
    'Retail Loss Prevention Specialists',
    'Treasurers and Controllers',
    'Art Directors',
    'Avionics Technicians',
    'Biomass Power Plant Managers',
    'Clinical Research Coordinators',
    'Construction and Building Inspectors',
    'Food Scientists and Technologists',
    'Gas Plant Operators',
    'Geographers',
    'Loan Officers',
    'Lodging Managers',
    'Nuclear Medicine Technologists',
    'Ophthalmic Medical Technologists',
    'Ophthalmologists, Except Pediatric',
    'Physical Therapists',
    'Print Binding and Finishing Workers',
    'Sales Managers',
    'Social and Human Service Assistants',
    'Supply Chain Managers',
    'Tax Examiners and Collectors, and Revenue Agents',
    'Travel Guides',
    'Weatherization Installers and Technicians',
    'Acute Care Nurses',
    'Agricultural Technicians',
    'Brownfield Redevelopment Specialists and Site Managers',
    'Cabinetmakers and Bench Carpenters',
    'Commercial Pilots',
    'Control and Valve Installers and Repairers, Except Mechanical Door',
    'Dentists, General',
    'Editors',
    'Electrical and Electronics Installers and Repairers, Transportation Equipment',
    'Elevator and Escalator Installers and Repairers',
    'Epidemiologists',
    'First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers',
    'Graphic Designers',
    'Healthcare Social Workers',
    'Industrial Production Managers',
    'Library Technicians',
    'Locksmiths and Safe Repairers',
    'Loss Prevention Managers',
    'Maintenance Workers, Machinery',
    'Medical Equipment Preparers',
    'Midwives',
    'Naturopathic Physicians',
    'New Accounts Clerks',
    'News Analysts, Reporters, and Journalists',
    'Nuclear Technicians',
    'Orthotists and Prosthetists',
    'Pharmacists',
    'Podiatrists',
    'Probation Officers and Correctional Treatment Specialists',
    'Secretaries and Administrative Assistants, Except Legal, Medical, and Executive',
    'Semiconductor Processing Technicians',
    'Solar Sales Representatives and Assessors',
    'Solar Thermal Installers and Technicians',
    'Transit and Railroad Police',
    'Farmers, Ranchers, and Other Agricultural Managers',
    'Insurance Claims and Policy Processing Clerks',
    'Adhesive Bonding Machine Operators and Tenders',
    'Aircraft Cargo Handling Supervisors',
    'Bus and Truck Mechanics and Diesel Engine Specialists',
    'Cardiovascular Technologists and Technicians',
    'Chemical Equipment Operators and Tenders',
    'Chief Executives',
    'Communications Teachers, Postsecondary',
    'Door-to-Door Sales Workers, News and Street Vendors, and Related Workers',
    'Emergency Management Directors',
    'Etchers and Engravers',
    'Fine Artists, Including Painters, Sculptors, and Illustrators',
    'Forest and Conservation Workers',
    'Forest Fire Inspectors and Prevention Specialists',
    'Gambling Managers',
    'Home Appliance Repairers',
    'Human Resources Specialists',
    'Instructional Coordinators',
    'Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
    'Medical Equipment Repairers',
    'Mental Health Counselors',
    'Millwrights',
    'Mobile Heavy Equipment Mechanics, Except Engines',
    'Motorboat Mechanics and Service Technicians',
    'Nurse Midwives',
    'Patternmakers, Wood',
    'Payroll and Timekeeping Clerks',
    'Phlebotomists',
    'Photographers',
    'Poets, Lyricists and Creative Writers',
    'Postal Service Clerks',
    'Postal Service Mail Sorters, Processors, and Processing Machine Operators',
    'Production, Planning, and Expediting Clerks',
    'Prosthodontists',
    'Radiologic Technologists and Technicians',
    'Real Estate Sales Agents',
    'Registered Nurses',
    'Rolling Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Shipping, Receiving, and Inventory Clerks',
    'Talent Directors',
    'Tax Preparers',
    'Team Assemblers',
    'Telecommunications Line Installers and Repairers',
    'Telephone Operators',
    'Tool and Die Makers',
    'Water and Wastewater Treatment Plant and System Operators',
    'Wind Turbine Service Technicians',
    'Music Directors and Composers',
    'First-Line Supervisors of Firefighting and Prevention Workers',
    'Captains, Mates, and Pilots of Water Vessels',
    'Aircraft Structure, Surfaces, Rigging, and Systems Assemblers',
    'Urologists',
    'Surgical Assistants',
    'Transportation Security Screeners',
    'Buyers and Purchasing Agents, Farm Products',
    'Community Health Workers',
    'Credit Counselors',
    'Energy Auditors',
    'Freight Forwarders',
    'Funeral Home Managers',
    'Insurance Underwriters',
    'Landscape Architects',
    'Lawyers',
    'Parking Enforcement Workers',
    'Recreational Therapists',
    'Sociologists',
    'Spa Managers',
    'Special Education Teachers, Middle School',
    'Career/Technical Education Teachers, Postsecondary',
    'Chemical Technicians',
    'Compensation and Benefits Managers',
    'Customer Service Representatives',
    'Education and Childcare Administrators, Preschool and Daycare',
    'File Clerks',
    'Film and Video Editors',
    'First-Line Supervisors of Non-Retail Sales Workers',
    'Food Service Managers',
    'General and Operations Managers',
    'Hearing Aid Specialists',
    'Heating, Air Conditioning, and Refrigeration Mechanics and Installers',
    'Inspectors, Testers, Sorters, Samplers, and Weighers',
    'Judicial Law Clerks',
    'Medical Assistants',
    'Museum Technicians and Conservators',
    'Nuclear Monitoring Technicians',
    'Paralegals and Legal Assistants',
    'Parts Salespersons',
    'Police Identification and Records Officers',
    'Printing Press Operators',
    'Psychiatrists',
    'Range Managers',
    'Sustainability Specialists',
    'Appraisers and Assessors of Real Estate',
    'Administrative Law Judges, Adjudicators, and Hearing Officers',
    'Advanced Practice Psychiatric Nurses',
    'Agents and Business Managers of Artists, Performers, and Athletes',
    'Agricultural Inspectors',
    'Aircraft Mechanics and Service Technicians',
    'Airline Pilots, Copilots, and Flight Engineers',
    'Animal Breeders',
    'Anthropology and Archeology Teachers, Postsecondary',
    'Arbitrators, Mediators, and Conciliators',
    'Biological Science Teachers, Postsecondary',
    'Chefs and Head Cooks',
    'Chiropractors',
    'Clergy',
    'Construction Managers',
    'Coroners',
    'Correctional Officers and Jailers',
    'Correspondence Clerks',
    'Craft Artists',
    'Customs and Border Protection Officers',
    'Dietetic Technicians',
    'Education Teachers, Postsecondary',
    'Electromechanical Equipment Assemblers',
    'Elementary School Teachers, Except Special Education',
    'Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic',
    'First-Line Supervisors of Correctional Officers',
    'Fish and Game Wardens',
    'Food Science Technicians',
    'Fundraisers',
    'Hospitalists',
    'Library Assistants, Clerical',
    'Log Graders and Scalers',
    'Mail Clerks and Mail Machine Operators, Except Postal Service',
    'Merchandise Displayers and Window Trimmers',
    'Ophthalmic Medical Technicians',
    'Oral and Maxillofacial Surgeons',
    'Order Clerks',
    'Pharmacy Aides',
    'Pharmacy Technicians',
    'Property, Real Estate, and Community Association Managers',
    'Psychiatric Technicians',
    'Railroad Conductors and Yardmasters',
    'Real Estate Brokers',
    'Recreational Vehicle Service Technicians',
    'Rehabilitation Counselors',
    'Respiratory Therapists',
    'Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products',
    'Sociology Teachers, Postsecondary',
    'Stone Cutters and Carvers, Manufacturing',
    'Switchboard Operators, Including Answering Service',
    'Tool Grinders, Filers, and Sharpeners',
    'Transportation, Storage, and Distribution Managers',
    'Claims Adjusters, Examiners, and Investigators',
    'First-Line Supervisors of Farming, Fishing, and Forestry Workers',
    'Librarians and Media Collections Specialists',
    'Tutors',
    'Administrative Services Managers',
    'Adult Basic Education, Adult Secondary Education, and English as a Second Language Instructors',
    'Anesthesiologist Assistants',
    'Coating, Painting, and Spraying Machine Setters',
    'Operators, and Tenders',
    'English Language and Literature Teachers, Postsecondary',
    'Fashion Designers',
    'Middle School Teachers, Except Special and Career/Technical Education',
    'Model Makers, Wood',
    'Motion Picture Projectionists',
    'Political Scientists',
    'Writers and Authors',
    'Aviation Inspectors',
    'Camera Operators, Television, Video, and Film',
    'Child, Family, and School Social Workers',
    'Counter and Rental Clerks',
    'Criminal Justice and Law Enforcement Teachers, Postsecondary',
    'Cytogenetic Technologists',
    'Dental Hygienists',
    'Education Administrators, Postsecondary',
    'Eligibility Interviewers, Government Programs',
    'Farm Labor Contractors',
    'Gas Compressor and Gas Pumping Station Operators',
    'Genetic Counselors',
    'Health Education Specialists',
    'Health Specialties Teachers, Postsecondary',
    'Labor Relations Specialists',
    'Legal Secretaries and Administrative Assistants',
    'Low Vision Therapists, Orientation and Mobility Specialists, and Vision Rehabilitation Therapists',
    'Maintenance and Repair Workers, General',
    'Medical Transcriptionists',
    'Molding, Coremaking, and Casting Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Morticians, Undertakers, and Funeral Arrangers',
    'Nurse Practitioners',
    'Pediatricians, General',
    'Procurement Clerks',
    'Public Relations Specialists',
    'Recycling Coordinators',
    'Residential Advisors',
    'Timing Device Assemblers and Adjusters',
    'Airfield Operations Specialists',
    'Animal Control Workers',
    'Art, Drama, and Music Teachers, Postsecondary',
    'Bookkeeping, Accounting, and Auditing Clerks',
    'Cargo and Freight Agents',
    'Coin, Vending, and Amusement Machine Servicers and Repairers',
    'Concierges',
    'Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders',
    'Dental Assistants',
    'Dispatchers, Except Police, Fire, and Ambulance',
    'Endoscopy Technicians',
    'Environmental Science Teachers, Postsecondary',
    'Financial Managers',
    'First-Line Supervisors of Food Preparation and Serving Workers',
    'First-Line Supervisors of Helpers, Laborers, and Material Movers, Hand',
    'First-Line Supervisors of Material-Moving Machine and Vehicle Operators',
    'First-Line Supervisors of Personal Service Workers',
    'Flight Attendants',
    'Floral Designers',
    'Foresters',
    'Gambling and Sports Book Writers and Runners',
    'Gambling Surveillance Officers and Gambling Investigators',
    'Glass Blowers, Molders, Benders, and Finishers',
    'Hairdressers, Hairstylists, and Cosmetologists',
    'Helpers--Installation, Maintenance, and Repair Workers',
    'Helpers--Roofers',
    'Media Programming Directors',
    'Medical Appliance Technicians',
    'Medical Secretaries and Administrative Assistants',
    'Meeting, Convention, and Event Planners',
    'Music Therapists',
    'Opticians, Dispensing',
    'Outdoor Power Equipment and Other Small Engine Mechanics',
    'Packers and Packagers, Hand',
    'Passenger Attendants',
    'Receptionists and Information Clerks',
    'Recreation Workers',
    'Speech-Language Pathology Assistants',
    'Tank Car, Truck, and Ship Loaders',
    'Technical Writers',
    'Training and Development Specialists',
    'Transportation Inspectors',
    'Ushers, Lobby Attendants, and Ticket Takers',
    'Allergists and Immunologists',
    "Police and Sheriff's Patrol Officers",
    'Court, Municipal, and License Clerks',
    'Stockers and Order Fillers',
    'Acupuncturists',
    'Adapted Physical Education Specialists',
    'Amusement and Recreation Attendants',
    'Animal Caretakers',
    'Athletic Trainers',
    'Baggage Porters and Bellhops',
    'Bartenders',
    'Bill and Account Collectors',
    'Broadcast Announcers and Radio Disc Jockeys',
    'Choreographers',
    'Clinical and Counseling Psychologists',
    'Clinical Nurse Specialists',
    'Coaches and Scouts',
    'Conveyor Operators and Tenders',
    'Cooks, Private Household',
    'Diagnostic Medical Sonographers',
    'Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
    'Electrical and Electronic Equipment Assemblers',
    'Electrical Power-Line Installers and Repairers',
    'Embalmers',
    'Exercise Trainers and Group Fitness Instructors',
    'Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers',
    'Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders',
    'Family Medicine Physicians',
    'Firefighters',
    'First-Line Supervisors of Construction Trades and Extraction Workers',
    'First-Line Supervisors of Production and Operating Workers',
    'Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders',
    'Food Cooking Machine Operators and Tenders',
    'Forging Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders',
    'Gambling Cage Workers',
    'Gambling Change Persons and Booth Cashiers',
    'Grinding and Polishing Workers, Hand',
    'Hazardous Materials Removal Workers',
    'Helpers--Production Workers',
    'Historians',
    'History Teachers, Postsecondary',
    'Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop',
    'Industrial Truck and Tractor Operators',
    'Insurance Appraisers, Auto Damage',
    'Judges, Magistrate Judges, and Magistrates',
    'Kindergarten Teachers, Except Special Education',
    'Licensed Practical and Licensed Vocational Nurses',
    'Makeup Artists, Theatrical and Performance',
    'Marriage and Family Therapists',
    'Motorcycle Mechanics',
    'Musical Instrument Repairers and Tuners',
    'Nurse Anesthetists',
    'Obstetricians and Gynecologists',
    'Occupational Therapy Assistants',
    'Office Clerks, General',
    'Orthodontists',
    'Physical Therapist Aides',
    'Political Science Teachers, Postsecondary',
    'Pourers and Casters, Metal',
    'Proofreaders and Copy Markers',
    'Purchasing Agents, Except Wholesale, Retail, and Farm Products',
    'Rail Yard Engineers, Dinkey Operators, and Hostlers',
    'Recreation and Fitness Studies Teachers, Postsecondary',
    'Retail Salespersons',
    'Sheet Metal Workers',
    'Solar Photovoltaic Installers',
    'Stationary Engineers and Boiler Operators',
    'Tellers',
    'Tire Builders',
    'Title Examiners, Abstractors, and Searchers',
    'Veterinarians',
    'Veterinary Assistants and Laboratory Animal Caretakers',
    'Wellhead Pumpers',
    'Credit Authorizers, Checkers, and Clerks',
    'First-Line Supervisors of Gambling Services Workers',
    'Welders, Cutters, Solderers, and Brazers',
    'Ambulance Drivers and Attendants, Except Emergency Medical Technicians',
    'Anesthesiologists',
    'Animal Trainers',
    'Automotive and Watercraft Service Attendants',
    'Automotive Glass Installers and Repairers',
    'Bailiffs',
    'Bicycle Repairers',
    'Bridge and Lock Tenders',
    'Butchers and Meat Cutters',
    'Cashiers',
    'Cement Masons and Concrete Finishers',
    'Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders',
    'Cooks, Restaurant',
    'Cooks, Short Order',
    'Court Reporters and Simultaneous Captioners',
    'Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Demonstrators and Product Promoters',
    'Dental Laboratory Technicians',
    'Dining Room and Cafeteria Attendants and Bartender Helpers',
    'Food Batchmakers',
    'Food Servers, Nonrestaurant',
    'Funeral Attendants',
    'Furniture Finishers',
    'Heavy and Tractor-Trailer Truck Drivers',
    'Highway Maintenance Workers',
    'Interpreters and Translators',
    'Layout Workers, Metal and Plastic',
    'Occupational Therapy Aides',
    'Operating Engineers and Other Construction Equipment Operators',
    'Packaging and Filling Machine Operators and Tenders',
    'Potters, Manufacturing',
    'Sawing Machine Setters, Operators, and Tenders, Wood',
    'Surgical Technologists',
    'Telemarketers',
    'Waiters and Waitresses',
    'Welding, Soldering, and Brazing Machine Setters, Operators, and Tenders',
    'Fast Food and Counter Workers',
    'Jewelers and Precious Stone and Metal Workers',
    'Plumbers, Pipefitters, and Steamfitters',
    'Actors',
    'Agricultural Equipment Operators',
    'Athletes and Sports Competitors',
    'Bakers',
    'Barbers',
    'Baristas',
    'Boilermakers',
    'Brickmasons and Blockmasons',
    'Bus Drivers, Transit and Intercity',
    'Carpenters',
    'Carpet Installers',
    'Childcare Workers',
    'Cleaners of Vehicles and Equipment',
    'Coil Winders, Tapers, and Finishers',
    'Commercial Divers',
    'Construction Laborers',
    'Continuous Mining Machine Operators',
    'Cooks, Fast Food',
    'Cooks, Institution and Cafeteria',
    'Costume Attendants',
    'Couriers and Messengers',
    'Crane and Tower Operators',
    'Crossing Guards and Flaggers',
    'Cutters and Trimmers, Hand',
    'Dancers',
    'Derrick Operators, Oil and Gas',
    'Dishwashers',
    'Dredge Operators',
    'Driver/Sales Workers',
    'Drywall and Ceiling Tile Installers',
    'Earth Drillers, Except Oil and Gas',
    'Electricians',
    'Excavating and Loading Machine and Dragline Operators, Surface Mining',
    'Explosives Workers, Ordnance Handling Experts, and Blasters',
    'Fallers',
    'Farmworkers and Laborers, Crop, Nursery, and Greenhouse',
    'Farmworkers, Farm, Ranch, and Aquacultural Animals',
    'Fence Erectors',
    'Fiberglass Laminators and Fabricators',
    'First-Line Supervisors of Housekeeping and Janitorial Workers',
    'Fishing and Hunting Workers',
    'Floor Layers, Except Carpet, Wood, and Hard Tiles',
    'Floor Sanders and Finishers',
    'Food Preparation Workers',
    'Foundry Mold and Coremakers',
    'Gambling Dealers',
    'Gem and Diamond Workers',
    'Glaziers',
    'Graders and Sorters, Agricultural Products',
    'Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters',
    'Helpers--Carpenters',
    'Helpers--Electricians',
    'Helpers--Extraction Workers',
    'Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons',
    'Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters',
    'Hoist and Winch Operators',
    'Home Health Aides',
    'Insulation Workers, Floor, Ceiling, and Wall',
    'Insulation Workers, Mechanical',
    'Janitors and Cleaners, Except Maids and Housekeeping Cleaners',
    'Laborers and Freight, Stock, and Material Movers, Hand',
    'Landscaping and Groundskeeping Workers',
    'Laundry and Dry-Cleaning Workers',
    'Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers',
    'Light Truck Drivers',
    'Loading and Moving Machine Operators, Underground Mining',
    'Locker Room, Coatroom, and Dressing Room Attendants',
    'Locomotive Engineers',
    'Logging Equipment Operators',
    'Machine Feeders and Offbearers',
    'Maids and Housekeeping Cleaners',
    'Manicurists and Pedicurists',
    'Manufactured Building and Mobile Home Installers',
    'Massage Therapists',
    'Meat, Poultry, and Fish Cutters and Trimmers',
    'Mechanical Door Repairers',
    'Metal-Refining Furnace Operators and Tenders',
    'Models',
    'Molders, Shapers, and Casters, Except Metal and Plastic',
    'Motorboat Operators',
    'Musicians and Singers',
    'Nannies',
    'Nursing Assistants',
    'Orderlies',
    'Painters, Construction and Maintenance',
    'Painting, Coating, and Decorating Workers',
    'Paper Goods Machine Setters, Operators, and Tenders',
    'Paperhangers',
    'Parking Attendants',
    'Paving, Surfacing, and Tamping Equipment Operators',
    'Personal Care Aides',
    'Pest Control Workers',
    'Pesticide Handlers, Sprayers, and Applicators, Vegetation',
    'Pile Driver Operators',
    'Pipelayers',
    'Plasterers and Stucco Masons',
    'Plating Machine Setters, Operators, and Tenders, Metal and Plastic',
    'Postal Service Mail Carriers',
    'Preschool Teachers, Except Special Education',
    'Pressers, Textile, Garment, and Related Materials',
    'Psychiatric Aides',
    'Rail Car Repairers',
    'Rail-Track Laying and Maintenance Equipment Operators',
    'Railroad Brake, Signal, and Switch Operators and Locomotive Firers',
    'Recycling and Reclamation Workers',
    'Refractory Materials Repairers, Except Brickmasons',
    'Refuse and Recyclable Material Collectors',
    'Reinforcing Iron and Rebar Workers',
    'Riggers',
    'Rock Splitters, Quarry',
    'Roof Bolters, Mining',
    'Roofers',
    'Rotary Drill Operators, Oil and Gas',
    'Roustabouts, Oil and Gas',
    'Sailors and Marine Oilers',
    'Security Guards',
    'Segmental Pavers',
    'Septic Tank Servicers and Sewer Pipe Cleaners',
    'Sewers, Hand',
    'Sewing Machine Operators',
    'Shampooers',
    'Shoe and Leather Workers and Repairers',
    'Shoe Machine Operators and Tenders',
    'Skincare Specialists',
    'Slaughterers and Meat Packers',
    'Stonemasons',
    'Structural Iron and Steel Workers',
    'Structural Metal Fabricators and Fitters',
    'Subway and Streetcar Operators',
    'Tailors, Dressmakers, and Custom Sewers',
    'Tapers',
    'Terrazzo Workers and Finishers',
    'Textile Bleaching and Dyeing Machine Operators and Tenders',
    'Textile Knitting and Weaving Machine Setters, Operators, and Tenders',
    'Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders',
    'Tile and Stone Setters',
    'Tire Repairers and Changers',
    'Tour Guides and Escorts',
    'Transportation Vehicle, Equipment and Systems Inspectors, Except Aviation',
    'Tree Trimmers and Pruners',
    'Umpires, Referees, and Other Sports Officials',
    'Upholsterers',
    'Watch and Clock Repairers'
  ];

  static List<String> getSuggestions(String query) {
    return List.of(skillsList).where((skill) {
      String skillLower = skill.toLowerCase();
      String queryLower = query.toLowerCase();
      return skillLower.contains(queryLower);
    }).toList();
  }
}
